spring:
  flyway:
    locations: classpath:db/migration
  datasource:
    username: root
    password: root
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database: H2
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: root